### ISSUE TITLE
Reproducing CIFAR-10

### ISSUE THREAD

**Issue by YinghuaGao** [hsouri/Sleeper-Agent#1]
Hi! authors. Thanks for your nice work. I really enjoy studying Sleeper Agent. I have a question about the experiments. I'd like to reproduce the results in  Table1. I run the code with command "CUDA_VISIBLE_DEVICES=0 python sleeper_agent.py --backdoor_poisoning --retrain_from_init --defend_features_only --disable_adaptive_attack", but I get ASR close to 100%, which is higher than 85.27 reported in the paper.  Looking forward to your advice.

**Comment by hsouri** [comment]
Hi, thank you for your comment. As we explained in our paper the reported ASR is an average over more than 20 trials. It is true that for some source_target pairs, the success rate is 99%. Therefore, if you want to reproduce the same results you need to run 24-32 trials with random source_target pairs and take the average.
