### ISSUE TITLE
The relation between surrogate network and victim model

### ISSUE THREAD

**Issue by yubangji123** [hsouri/Sleeper-Agent#2]
Dear authors,

I am reading your paper and implementing your method, I have some questions about your attacking framework.

What are the relations between the surrogate network and victim model? From your paper, it seems like that the surrogate network will craft the perturbations and add them to the clean target images through the bi-level training. After that, the attacker could utilize the perturbed target images to train a new victim model, which will be used to evaluate the poison attacking success rate, i.e., testing the source image with trigger patches. Is my understanding correct?

Glad to hear from you,
Thanks

**Comment by hsouri** [comment]
Yes, that is correct. We use the surrogate model only for poison crafting. When crafting is done we train a victim model (which could be the same architecture as the surrogate model or it could be a completely different architecture) on the poisoned trainset from scratch. The attack success rate is the average rate at which
patched source images are successfully classified as the target class.

**Comment by yubangji123** [comment]
I got it, thanks!
